import { findClusters } from './cluster-detection';
import { FREE_SPINS_AWARDED, FREE_SPINS_TRIGGER_COUNT, fsRetriggerAward } from './paytable';
import type { Rng } from '../../shared/math/rng';
import { pickSymbol, pickWildMultiplier, type SymbolId } from './symbols';
import {
  COLS, ROWS,
  type Cluster, type Grid, type SpinResult, type TumbleStep, type WildMultGrid,
} from './types';

function emptyWilds(): WildMultGrid {
  const w: WildMultGrid = [];
  for (let c = 0; c < COLS; c++) w.push(new Array(ROWS).fill(0));
  return w;
}

function randomGrid(rng: Rng): { grid: Grid; wilds: WildMultGrid } {
  const grid: Grid = [];
  const wilds = emptyWilds();
  for (let c = 0; c < COLS; c++) {
    const col: SymbolId[] = [];
    for (let r = 0; r < ROWS; r++) {
      const sym = pickSymbol(rng);
      col.push(sym);
      if (sym === 'WILD') wilds[c][r] = pickWildMultiplier(rng);
    }
    grid.push(col);
  }
  return { grid, wilds };
}

function cloneGrid(g: Grid): Grid {
  return g.map((col) => col.slice());
}

function cloneWilds(w: WildMultGrid): WildMultGrid {
  return w.map((col) => col.slice());
}

interface TumbleResult {
  next: Grid;
  nextWilds: WildMultGrid;
  /** Number of SCATTER symbols generated by this tumble's fill phase. */
  newScatters: number;
}

function applyTumble(
  grid: Grid,
  wilds: WildMultGrid,
  winningCells: ReadonlyArray<readonly [number, number]>,
  rng: Rng,
): TumbleResult {
  const removed: Set<string> = new Set();
  for (const [c, r] of winningCells) removed.add(`${c},${r}`);

  const next: Grid = [];
  const nextWilds: WildMultGrid = [];
  let newScatters = 0;

  for (let c = 0; c < COLS; c++) {
    const survivorSyms: SymbolId[] = [];
    const survivorMults: number[] = [];
    for (let r = 0; r < ROWS; r++) {
      if (!removed.has(`${c},${r}`)) {
        survivorSyms.push(grid[c][r]);
        survivorMults.push(wilds[c][r] || 0);
      }
    }
    const missing = ROWS - survivorSyms.length;
    const newSyms: SymbolId[] = [];
    const newMults: number[] = [];
    for (let i = 0; i < missing; i++) {
      const sym = pickSymbol(rng);
      newSyms.push(sym);
      newMults.push(sym === 'WILD' ? pickWildMultiplier(rng) : 0);
      if (sym === 'SCATTER') newScatters++;
    }
    // New symbols stack on top (lower row indices), survivors fall to bottom.
    next.push([...newSyms, ...survivorSyms]);
    nextWilds.push([...newMults, ...survivorMults]);
  }
  return { next, nextWilds, newScatters };
}

function uniqueWinningCells(clusters: Cluster[]): Array<readonly [number, number]> {
  const seen = new Set<string>();
  const out: Array<readonly [number, number]> = [];
  for (const cl of clusters) {
    for (const cell of cl.cells) {
      const k = `${cell[0]},${cell[1]}`;
      if (!seen.has(k)) {
        seen.add(k);
        out.push(cell);
      }
    }
  }
  return out;
}

function countScatters(grid: Grid): number {
  let n = 0;
  for (let c = 0; c < COLS; c++) {
    for (let r = 0; r < ROWS; r++) {
      if (grid[c][r] === 'SCATTER') n++;
    }
  }
  return n;
}


export interface SpinOptions {
  bet: number;
  rng: Rng;
  isFreeSpin?: boolean;
  /** Multiplier carried into this free spin (starts at 1). */
  startingMultiplier?: number;
}

/**
 * Runs a single spin with full tumble cascade.
 * In free-spin mode the multiplier starts at `startingMultiplier` (default 1)
 * and increments by 1 after each cascade that produced a win.
 *
 * Each WILD cell carries its own ×N multiplier (see `pickWildMultiplier`)
 * which is added — additively — into any cluster the wild participates in.
 * A cluster crossing two ×2 wilds, for example, multiplies its base payout
 * by 4. The FS step multiplier still stacks on top of this.
 */
export function spin(opts: SpinOptions): SpinResult {
  const { bet, rng, isFreeSpin = false } = opts;
  let multiplier = opts.startingMultiplier ?? 1;

  const { grid: initialGrid, wilds: initialWilds } = randomGrid(rng);
  let grid = initialGrid;
  let wilds = initialWilds;
  let totalScatters = countScatters(grid);
  const steps: TumbleStep[] = [];
  let totalWin = 0;
  let safety = 50;

  while (safety-- > 0) {
    const clusters = findClusters(grid, wilds, bet);
    if (clusters.length === 0) {
      steps.push({
        gridBefore: grid,
        wildsBefore: wilds,
        clusters: [],
        gridAfter: grid,
        wildsAfter: wilds,
        stepWin: 0,
        multiplier: isFreeSpin ? multiplier : 1,
      });
      break;
    }

    // In FS, redirect each cluster's wild multiplier into the *running*
    // game multiplier instead of multiplying that cluster's payout
    // directly: a ×5 wild in a cluster pushes the FS multiplier up by 5
    // (so it's now in effect for THIS cluster's payout AND every
    // subsequent cascade in this spin). In base play we keep the
    // existing per-cluster wild boost since there's no running mult.
    let stepMult: number;
    let baseWin: number;
    if (isFreeSpin) {
      let wildBonus = 0;
      for (const c of clusters) {
        if (c.wildMultiplier > 1) wildBonus += c.wildMultiplier;
      }
      multiplier += wildBonus;
      stepMult = multiplier;
      // Strip the per-cluster wild factor we no longer want — `c.payout`
      // is base × wildMultiplier; divide it back out so we're not
      // double-counting the wild contribution.
      baseWin = clusters.reduce((s, c) => s + c.payout / c.wildMultiplier, 0);
    } else {
      stepMult = 1;
      baseWin = clusters.reduce((s, c) => s + c.payout, 0);
    }
    const stepWin = baseWin * stepMult;
    totalWin += stepWin;

    const winningCells = uniqueWinningCells(clusters);
    const tumble = applyTumble(grid, wilds, winningCells, rng);
    const next = tumble.next;
    const nextWilds = tumble.nextWilds;
    totalScatters += tumble.newScatters;

    steps.push({
      gridBefore: grid,
      wildsBefore: wilds,
      clusters,
      gridAfter: next,
      wildsAfter: nextWilds,
      stepWin,
      multiplier: stepMult,
    });

    if (isFreeSpin) multiplier += 1;
    grid = next;
    wilds = nextWilds;
  }

  let triggeredFreeSpins = 0;
  if (!isFreeSpin && totalScatters >= FREE_SPINS_TRIGGER_COUNT) {
    triggeredFreeSpins = FREE_SPINS_AWARDED;
  } else if (isFreeSpin) {
    triggeredFreeSpins = fsRetriggerAward(totalScatters);
  }

  return {
    bet,
    isFreeSpin,
    initialGrid,
    initialWilds,
    steps,
    totalScattersLanded: totalScatters,
    triggeredFreeSpins,
    totalWin,
    endMultiplier: multiplier,
  };
}

/**
 * Build a visual-only spin result for the bonus-buy fake-trigger animation:
 * a random grid with the trigger threshold of SCATTERs planted in random
 * cells, and zero clusters/steps so the renderer's `playSpin()` plays the
 * initial-drop animation and stops. The cost was already debited by
 * `buyBonus()`; this spin pays nothing — its only job is to land scatters
 * on the board so the player sees the bonus condition before the cinematic.
 */
export function makeBonusBuyTriggerSpin(opts: {
  bet: number;
  rng: Rng;
  scattersCount: number;
  freeSpinsAwarded: number;
}): SpinResult {
  const { grid, wilds } = randomGrid(opts.rng);
  const cells: Array<[number, number]> = [];
  for (let c = 0; c < COLS; c++) for (let r = 0; r < ROWS; r++) cells.push([c, r]);
  for (let i = 0; i < opts.scattersCount && i < cells.length; i++) {
    const j = i + Math.floor(opts.rng.next() * (cells.length - i));
    [cells[i], cells[j]] = [cells[j], cells[i]];
    const [c, r] = cells[i];
    grid[c][r] = 'SCATTER';
    wilds[c][r] = 0;
  }
  return {
    bet: opts.bet,
    isFreeSpin: false,
    initialGrid: grid,
    initialWilds: wilds,
    steps: [],
    totalScattersLanded: opts.scattersCount,
    triggeredFreeSpins: opts.freeSpinsAwarded,
    totalWin: 0,
    endMultiplier: 1,
  };
}
