import { findClusters } from './cluster-detection';
import { FREE_SPINS_AWARDED, FREE_SPINS_TRIGGER_COUNT, fsRetriggerAward } from './paytable';
import { pickSymbol, type Rng } from './rng';
import type { SymbolId } from './symbols';
import { COLS, ROWS, type Cluster, type Grid, type SpinResult, type TumbleStep } from './types';

function randomGrid(rng: Rng): Grid {
  const g: Grid = [];
  for (let c = 0; c < COLS; c++) {
    const col: SymbolId[] = [];
    for (let r = 0; r < ROWS; r++) col.push(pickSymbol(rng));
    g.push(col);
  }
  return g;
}

function cloneGrid(g: Grid): Grid {
  return g.map((col) => col.slice());
}

interface TumbleResult {
  next: Grid;
  /** Number of SCATTER symbols generated by this tumble's fill phase. */
  newScatters: number;
}

function applyTumble(grid: Grid, winningCells: ReadonlyArray<readonly [number, number]>, rng: Rng): TumbleResult {
  const next = cloneGrid(grid);
  const removed: Set<string> = new Set();
  for (const [c, r] of winningCells) removed.add(`${c},${r}`);

  let newScatters = 0;
  for (let c = 0; c < COLS; c++) {
    const survivors: SymbolId[] = [];
    for (let r = 0; r < ROWS; r++) {
      if (!removed.has(`${c},${r}`)) survivors.push(next[c][r]);
    }
    const missing = ROWS - survivors.length;
    const newSyms: SymbolId[] = [];
    for (let i = 0; i < missing; i++) {
      const sym = pickSymbol(rng);
      newSyms.push(sym);
      if (sym === 'SCATTER') newScatters++;
    }
    // New symbols stack on top (lower row indices), survivors fall to bottom.
    next[c] = [...newSyms, ...survivors];
  }
  return { next, newScatters };
}

function uniqueWinningCells(clusters: Cluster[]): Array<readonly [number, number]> {
  const seen = new Set<string>();
  const out: Array<readonly [number, number]> = [];
  for (const cl of clusters) {
    for (const cell of cl.cells) {
      const k = `${cell[0]},${cell[1]}`;
      if (!seen.has(k)) {
        seen.add(k);
        out.push(cell);
      }
    }
  }
  return out;
}

function countScatters(grid: Grid): number {
  let n = 0;
  for (let c = 0; c < COLS; c++) {
    for (let r = 0; r < ROWS; r++) {
      if (grid[c][r] === 'SCATTER') n++;
    }
  }
  return n;
}


export interface SpinOptions {
  bet: number;
  rng: Rng;
  isFreeSpin?: boolean;
  /** Multiplier carried into this free spin (starts at 1). */
  startingMultiplier?: number;
}

/**
 * Runs a single spin with full tumble cascade.
 * In free-spin mode the multiplier starts at `startingMultiplier` (default 1)
 * and increments by 1 after each cascade that produced a win.
 */
export function spin(opts: SpinOptions): SpinResult {
  const { bet, rng, isFreeSpin = false } = opts;
  let multiplier = opts.startingMultiplier ?? 1;

  const initialGrid = randomGrid(rng);
  let grid = initialGrid;
  let totalScatters = countScatters(grid);
  const steps: TumbleStep[] = [];
  let totalWin = 0;
  let safety = 50;

  while (safety-- > 0) {
    const clusters = findClusters(grid, bet);
    if (clusters.length === 0) {
      steps.push({
        gridBefore: grid,
        clusters: [],
        gridAfter: grid,
        stepWin: 0,
        multiplier: isFreeSpin ? multiplier : 1,
      });
      break;
    }

    const baseWin = clusters.reduce((s, c) => s + c.payout, 0);
    const stepMult = isFreeSpin ? multiplier : 1;
    const stepWin = baseWin * stepMult;
    totalWin += stepWin;

    const winningCells = uniqueWinningCells(clusters);
    const tumble = applyTumble(grid, winningCells, rng);
    const next = tumble.next;
    totalScatters += tumble.newScatters;

    steps.push({
      gridBefore: grid,
      clusters,
      gridAfter: next,
      stepWin,
      multiplier: stepMult,
    });

    if (isFreeSpin) multiplier += 1;
    grid = next;
  }

  let triggeredFreeSpins = 0;
  if (!isFreeSpin && totalScatters >= FREE_SPINS_TRIGGER_COUNT) {
    triggeredFreeSpins = FREE_SPINS_AWARDED;
  } else if (isFreeSpin) {
    triggeredFreeSpins = fsRetriggerAward(totalScatters);
  }

  return {
    bet,
    isFreeSpin,
    initialGrid,
    steps,
    totalScattersLanded: totalScatters,
    triggeredFreeSpins,
    totalWin,
    endMultiplier: multiplier,
  };
}
